apiVersion: v1
kind: Namespace
metadata:
  name: kube-check-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-check-agent
  namespace: kube-check-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-check-agent-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-check-agent-binding
subjects:
  - kind: ServiceAccount
    name: kube-check-agent
    namespace: kube-check-system
roleRef:
  kind: ClusterRole
  name: kube-check-agent-role
  apiGroup: rbac.authorization.k8s.io
