apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-check-web
  namespace: kube-check-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-check-web
  template:
    metadata:
      labels:
        app: kube-check-web
    spec:
      containers:
      - name: web
        image: kube-check-frontend:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: kube-check-web
  namespace: kube-check-system
spec:
  type: Queue
  selector:
    app: kube-check-web
  ports:
  - port: 80
    targetPort: 3000
